spring:
  application: 
    name: customerdemo
  datasource:
    url: jdbc:postgresql://localhost:5432/Customerdb
    username: postgres
    password: POSTGRESQL1980
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true      
    properties:
      hibernate:
        format_sql: true  

server:
  port: 8085

